# Generated by Django 4.1.4 on 2023-02-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('appointment_data', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=100)),
                ('token_no', models.IntegerField()),
                ('problem', models.TextField()),
            ],
        ),
    ]
