# Generated by Django 4.1.4 on 2023-02-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
