# Generated by Django 4.1.4 on 2023-03-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_patient_address_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_id',
            field=models.IntegerField(null=True),
        ),
    ]
