# Generated by Django 4.1.4 on 2023-03-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_appointment_token_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.IntegerField(null=True),
        ),
    ]
