# Generated by Django 4.1.4 on 2023-03-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_appointment_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('allotment_date', models.CharField(max_length=100)),
                ('discharge_date', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
            ],
        ),
    ]
