# Generated by Django 4.1.4 on 2023-03-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
