# Generated by Django 4.1.4 on 2023-03-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('patients', models.CharField(max_length=100)),
            ],
        ),
    ]
