# Generated by Django 4.1.4 on 2023-03-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_patients_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('appointments', models.CharField(max_length=100)),
            ],
        ),
    ]
