# Generated by Django 4.1.4 on 2023-03-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_appointment_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('mobileNo', models.CharField(max_length=100)),
            ],
        ),
    ]
