# Generated by Django 4.1.4 on 2023-03-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_payment_delete_room_meat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient_name',
        ),
    ]
