# Generated by Django 4.1.4 on 2023-03-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_payments_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='service_description',
            new_name='cost_of_treatment',
        ),
    ]
