# Generated by Django 4.1.4 on 2023-03-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_payment_delete_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
