# Generated by Django 4.1.4 on 2023-03-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_patient_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_payment',
            name='date_inovice',
            field=models.DateField(default=1),
        ),
        migrations.AddField(
            model_name='patient_payment',
            name='payment_id',
            field=models.IntegerField(default=1),
        ),
    ]
