# Generated by Django 4.1.4 on 2023-03-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_patient_payment_date_inovice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_payment',
            name='date_inovice',
        ),
    ]
