# Generated by Django 4.1.4 on 2023-03-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_patient_payment_date_inovice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_payment',
            name='payment_id',
        ),
    ]
