# Generated by Django 4.1.4 on 2023-03-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_patient_payment_payment_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient_Payment',
            new_name='Patient_bill',
        ),
    ]
