# Generated by Django 4.1.4 on 2023-03-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_patient_bill_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('admission_date', models.CharField(max_length=100)),
                ('discharge_date', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('cost_of_treatment', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('advance_paid', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('card_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Patient_bill',
        ),
    ]
