# Generated by Django 4.1.4 on 2023-03-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_patient_payment_delete_patient_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_payment',
            name='invoice_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_payment',
            name='invoice_id',
            field=models.IntegerField(default=0),
        ),
    ]
